name: Reminder Worker

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes (UTC)
  workflow_dispatch:        # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production   # 👈 Must match the environment name where secrets are added

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reminder script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          python reminder.py
